### ISSUE TITLE
Cannot connect to dagger engine

### ISSUE THREAD

**Issue by everte** [wingyplus/dagger_ex#21]
Hello, I have been interested in trying out dagger for a while (from and for an elixir application) so I was very excited to to see someone actually implemented an sdk on top of the graphql api's. Many thanks!

Sadly I have some difficulties getting started. When I try the node example from the dagger documentation it works fine (just to make sure dagger is working etc).

When running elixir one I get the following error message:
```
** (RuntimeError) Cannot connect to Dagger engine, cause: :error
    (dagger_ex 0.2.0-dev) lib/dagger.ex:35: Dagger.connect!/1
    ci.exs:8: Ci.run/0
    (elixir 1.14.1) lib/code.ex:1245: Code.require_file/2
```

I used the following code, based on your Readme example:
```
#! /usr/bin/env elixir
Mix.install([
  {:dagger_ex, git: "https://github.com/wingyplus/dagger_ex", branch: "main"}
])

defmodule Ci do
  def run do
    client = Dagger.connect!()

    client
    |> Dagger.Query.container([])
    |> Dagger.Container.from(
      address: "hexpm/elixir:1.14.4-erlang-25.3-debian-buster-20230227-slim"
    )
    |> Dagger.Container.with_exec(args: ["elixir", "--version"])
    |> Dagger.Container.stdout()
    |> IO.puts()
  end
end

Ci.run()
```
I'm probably making a silly mistake somewhere!

**Comment by wingyplus** [comment]
Currently, the SDK have 2 ways to run the code:

1. Run with `dagger run <command ...>` where the `<command ...>` maybe `elixir script.exs` in this case. The Dagger engine setup session and run your code automatically.
2. Run by enable `_EXPERIMENTAL_DAGGER_CLI_BIN=dagger` environment variables.

I recommended to use `1.` since  they have a fancy ways to visualize the pipeline. For example, set `_EXPERIMENTAL_DAGGER_TUI=1` before running `dagger run ...` to enable interactive terminal UI. 

But when I write the documentation, I didn't found the ways to see debug log from Dagger engine except `2.`. That's why I wrote it to run as `2.`. 

The documentation will be improve in 0.2.0. Or help improving it is very welcome. :)
